# Generated by Django 4.0.2 on 2022-02-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='base',
            field=models.TextField(blank=True, null=True),
        ),
    ]
